stages:          # List of stages for jobs, and their order of execution
  - deploy


heroku:
 stage: deploy
 only:
 - master
 script:
 - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/cotizadorcmc.git
 - git push -f heroku master