stages:          # List of stages for jobs, and their order of execution
  - serverup


heroku:
 stage: 
   -serverup
 only:
   - master
 script:
   - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/<Your heroku app name>.git
   - git push -f heroku master